#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
#pragma config(Motor,  motorA,          leftMotor,     tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int lightControl;

void driveForward (int speed);
void findLine (int rotation);
bool rotateRight (int speed);
bool rotateLeft (int speed);
bool waitForLine (void);

task main()
{
	//samples current board light
	int lightSensorValue = SensorValue[lightSensor];
	lightControl = lightSensorValue - 15;

	motor[leftMotor] = 30;
	motor[rightMotor] = 30;
	wait1Msec(1000);

	while (1)
	{
		driveForward(60);
		findLine(28);
	}

}

void driveForward (int speed)
{
	while (SensorValue[lightSensor] <= lightControl)
	{
		//go forward
		motor[leftMotor] = speed;
		motor[rightMotor] = speed;
	}
	//stop, lost the line..
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
}

void findLine (int rotation)
{
	bool lineFound = false;

	lineFound = rotateRight(rotation);
	if (!lineFound)
		rotateLeft(rotation);
	else
		return;

	lineFound = rotateLeft(rotation);
	if (!lineFound)
		powerOff();

}

bool rotateRight (int speed)
{
	motor[rightMotor] = speed;
	motor[leftMotor] = speed * -1;
	bool retval = waitForLine ();
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
	return retval;

}

bool rotateLeft (int speed)
{
	motor[rightMotor] = speed * -1;
	motor[leftMotor] = speed;
	bool retval = waitForLine ();
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
	return retval;

}

bool waitForLine (void)
{
	int timeWaited = 0;
	while (SensorValue[lightSensor] > lightControl)
	{
		wait1Msec (1);
		timeWaited++;
		if (timeWaited > 350)
			return false;
	}
	return true;

}
